pool:
  vmImage: 'Ubuntu-18.04'

trigger:
  tags:
    include:
      - "*"
  branches:
    include:
      - refs/heads/*

pr:
  branches:
    include:
      - '*'

variables:
  # Variables imported from brewblox group:
  # DOCKER_USER
  # DOCKER_PASSWORD
  # PYPI_USER
  # PYPI_PASSWORD
  - group: brewblox

steps:
- task: UsePythonVersion@0
  inputs:
    addToPath: true
    versionSpec: '3.8'
    architecture: 'x64'

- bash: |
    BRANCH=$(echo $(Build.SourceBranch) | grep -oP "^refs/heads/\K.*")
    RELEASE=$(git describe --tags | grep "^[[:digit:]]*\.[[:digit:]]*\.[[:digit:]]$")
    TAG=$(echo $BRANCH | tr '/' '-' | tr '[:upper:]' '[:lower:]')
    set -o allexport; source .env; set +o allexport
    echo "##vso[task.setvariable variable=brewblox.image]$DOCKER_REPO"
    echo "##vso[task.setvariable variable=brewblox.branch]$BRANCH"
    echo "##vso[task.setvariable variable=brewblox.release]$RELEASE"
    echo "##vso[task.setvariable variable=brewblox.tag]#TAG"
  displayName: export build variables

- bash: |
    pip install pipenv
    pipenv install --system --dev --deploy
    pytest
  displayName: Run Pytest

- bash: |
    python setup.py sdist
  displayName: Build Python package

- bash: |
    echo $(DOCKER_PASSWORD) | docker login -u $(DOCKER_USER) --password-stdin
  displayName: Docker login
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

- bash: |
    pipenv lock --requirements > docker/requirements.txt
    docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    docker buildx create --use
    docker buildx inspect --bootstrap
    docker buildx build --tag $(brewblox.image):$(brewblox.tag) --push --platform linux/amd64,linux/arm/v7 docker
  displayName: Deploy branch to Docker Hub on any push to the GitHub repository
  condition: and(succeeded(), variables['brewblox.branch'], not(variables['brewblox.release']))
  env:
    DOCKER_CLI_EXPERIMENTAL: enabled
# - bash: >
#     brewblox-dev localbuild
#     --arch amd --arch arm
#     --tag newest-tag --tag $(brewblox.release)
#     --push
#   displayName: Deploy newest-tag and version tag to Docker Hub on tagged commits
#   condition: and(succeeded(), variables['brewblox.release'])

# - bash: >
#     brewblox-dev localbuild
#     --arch amd --arch arm
#     --branch-tag
#     --push
#   displayName: Deploy branch to Docker Hub on any push to the GitHub repository
#   condition: and(succeeded(), variables['brewblox.branch'], not(variables['brewblox.release']))
#   env:
#   # brewblox-tools looks for $TRAVIS_BRANCH to determine branch tag
#     TRAVIS_BRANCH: $(brewblox.branch)

- bash: |
    pip install twine
    twine upload -u $(PYPI_USER) -p $(PYPI_PASSWORD) --skip-existing dist/*
  displayName: Deploy to PyPi
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
