pool:
  vmImage: 'Ubuntu-18.04'

strategy:
  matrix:
    Python37:
      python.version: '3.7'
    Python38:
      python.version: '3.8'

trigger:
  tags:
    include:
      - "*"
  branches:
    include:
      - refs/heads/*

pr:
  branches:
    include:
      - '*'

variables:
  # Variables imported from brewblox group:
  # DOCKER_USER
  # DOCKER_PASSWORD
  # PYPI_USER
  # PYPI_PASSWORD
  - group: brewblox

steps:
- task: UsePythonVersion@0
  inputs:
    addToPath: true
    versionSpec: '$(python.version)'
    architecture: 'x64'

- bash: |
    set -o allexport; source .env; set +o allexport
    echo "##vso[task.setvariable variable=DOCKER_REPO]$DOCKER_REPO"
    echo "##vso[task.setvariable variable=GITHUB_REPO]$GITHUB_REPO"
  displayName: Export .env variables

- bash: |
    BRANCH=$(echo $(Build.SourceBranch) | grep -oP "^refs/heads/\K.*")
    TAG=$(echo $BRANCH | tr '/' '-' | tr '[:upper:]' '[:lower:]')
    echo "##vso[task.setvariable variable=BRANCH]$BRANCH"
    echo "##vso[task.setvariable variable=TAG]$TAG"
  displayName: Export build variables

- bash: |
    pip install -U pip
    pip install poetry
    poetry build --format sdist
  displayName: Build Python package

- bash: pytest
  displayName: Run Pytest

- bash: cp -rf dist/ docker/
  displayName: Copy files to docker context
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

- bash: |
    curl -L -o ~/.docker/cli-plugins/docker-buildx --create-dirs ${BUILDX_URL}
    chmod a+x ~/.docker/cli-plugins/docker-buildx
    docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    docker buildx create --use
    docker buildx inspect --bootstrap
  displayName: Prepare buildx
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  env:
    BUILDX_URL: https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64

- bash: |
    echo $(DOCKER_PASSWORD) | docker login -u $(DOCKER_USER) --password-stdin
  displayName: Docker login
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

- bash: >-
    docker buildx build
    --tag $(DOCKER_REPO):$(python.version)-$(TAG)
    --build-arg python_version="$(python.version)"
    --build-arg service_info="$(VERSION) @ $(date)"
    --push
    --platform linux/amd64,linux/arm/v7
    docker
  displayName: Deploy Docker images with branch tags
  condition: and(succeeded(), variables['BRANCH'])

- bash: |
    pip install twine
    twine upload -u $(PYPI_USER) -p $(PYPI_PASSWORD) --skip-existing dist/*
  displayName: Deploy to PyPi
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'), eq(variables['python.version'], '3.7'))
