name: CI build

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [develop]

jobs:
  build:
    # if: github.repository_owner == 'BrewBlox'
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry wheel
          poetry install

      - name: Test
        run: |
          poetry run pytest
          poetry run flake8

      - name: Deploy to PyPi
        if: github.event_name != 'pull_request'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
